#!/bin/bash

apt-get update -y
apt-get install openssh-server -y

sudo swapoff -a
sudo rm -rf /swapfile
sudo fallocate -l 8G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
sudo apt-get install bleachbit -y
~                                    
